### ISSUE TITLE
TypeError: Cannot read property 'collection' of undefined

### ISSUE THREAD

**Issue by LSheNNawY** [hkbu-kennycheng/sails-firestore#1]
i have this error when i'm trying to deal with collections:
```
fn: async function (inputs) {

    var db = User.getDatastore().manager;

    var users = await db.collection('users').get();
    return users;
}
```

**Comment by hkbu-kennycheng** [comment]
You could simply call Users.find() to receive all the users.

For references, please see https://sailsjs.com/documentation/reference/waterline-orm/models.

**Comment by hkbu-kennycheng** [comment]
If you have any questions please feel free to open an issue.
